# -*- coding: utf-8 -*-
"""Practica_M2S3.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11wK3ltTkNX6G5Zxq2WDIUig19TnW6ZlR
"""

#1 Crea una lista productos que contenga al menos cinco nombres de productos (1 punto).
lista_productos = []
cont = 1
while True:
  producto = input("Ingresa el nombre del producto (X para Salir): ")
  if producto.upper() == "X" :
      break
  lista_productos.append(producto)
  cont = cont + 1
  if cont == 6:
    break

print("Tu lista: ")
print(lista_productos)

#2 Agrega dos productos más a la lista productos y luego rescata los primeros tres elementos
# en una nueva lista llamada productos_destacados (1 puntos).

while True:
  producto = input("Ingresa el nombre del producto (X para Salir): ")
  if producto.upper() == "X" :
      break
  lista_productos.append(producto)

print( "\nLista Actualizada : ")
print(lista_productos)

i=0
productos_destacados= []
productos_destacados.clear()
for producto in lista_productos:
  if i<3:
    productos_destacados.append(producto)
    i=i+1
print( "\nProductos destacados: ")
print(productos_destacados)

#3 Crea un diccionario inventario donde cada clave sea el nombre de un producto y el valor sea
#. la cantidad en stock. Incluye al menos cinco productos con sus cantidades (2 puntos).

inventario = {}
for producto in lista_productos:
  inventario[producto] = 0

for producto in inventario:
  while True:
    try:
      cantidad = int(input(f"Ingresa la cantidad de {producto}: "))
      if cantidad >= 0:
         break
      else:
         print("La cantidad no puede ser negativa. Intenta de nuevo.")
    except ValueError:
      print("Entrada no válida. Intenta de nuevo.")
  inventario[producto] = cantidad
print(inventario)

#Agrega un nuevo producto al diccionario inventario y muestra la cantidad en stock de un
#producto específico (elige cualquiera de los cinco productos iniciales) (1 punto).


nuevo_producto = input("Ingresa el nombre del nuevo producto: ")
inventario[nuevo_producto] = 0

try:
  while True:
    cantidad = int(input(f"Ingresa la cantidad de {nuevo_producto}: "))
    if cantidad >= 0:
      break
    else:
      print("La cantidad no puede ser negativa. Intenta de nuevo.")
except ValueError:
  print("Entrada no válida. Intenta de nuevo.")

inventario[nuevo_producto] = cantidad

j=1
lproductos = []
for producto in inventario:
  print (str(j) + ' - ' + producto + ": " + str(inventario[producto]) + "\n")
  lproductos.append(producto)
  j=j+1

try:
  while True:
    indice = int(input(f"Ingresa el indice del producto a modificar: "))
    if indice >= 0:
      break
    else:
      print("El número no puede ser negativo. Intenta de nuevo.")
except ValueError:
  print("Entrada no válida. Intenta de nuevo.")

try:
  while True:
    cantidad = int(input(f"Ingresa la cantidad de {lproductos[indice-1]}: "))
    if cantidad >= 0:
      break
    else:
      print("La cantidad no puede ser negativa. Intenta de nuevo.")
except ValueError:
  print("Entrada no válida. Intenta de nuevo.")

inventario[lproductos[indice-1]] = cantidad


try:
  while True:
    indice = int(input(f"Ingresa el indice del producto a consultar: "))
    if indice >= 0:
      print("\nInventario del producto " +lproductos[indice-1]+  ": " + str(inventario[lproductos[indice-1]]) )
      break
    else:
      print("El número no puede ser negativo. Intenta de nuevo.")
except ValueError:
  print("Entrada no válida. Intenta de nuevo.")

#5. Crea una tupla categorías que contenga las categorías de los productos (por ejemplo,
#“Electrónica”, “Ropa”, “Alimentos”). Rescata y muestra la segunda categoría (1 punto).

categorias  = ("Electronica", "Ropa", "Alimentos")
print(categorias[1])

#6. Empaqueta las categorías en una tupla y luego desempaquétalas en variables individuales
#para que cada categoría quede asignada a una variable (2 puntos).

categoria1 = categorias[0]
categoria2 = categorias[1]
categoria3 = categorias[2]

print(categoria1)
print(categoria2)
print(categoria3)

#Crea un set productos_unicos a partir de la lista productos y verifica que no existan
#elementos duplicados (1 punto).
print(lista_productos)
productos_unicos = []
for producto in lista_productos:
  if producto not in productos_unicos:
    productos_unicos.append(producto)

print(productos_unicos)

#Usa comprensión de listas para crear una lista productos_mayusculas que contenga los
#nombres de productos en mayúsculas (1 punto)

productos_mayusculas = [producto.upper() for producto in productos_unicos]
print(productos_mayusculas)